[global]
config_version=3
backend=TensorRT
backend_auto_fallback=no
logging=no
default_slot=2

[slot_1]
profile_name=补帧 2×
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=0
chain_1_max_fps=0
chain_1_rife=yes
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
chain_1_rife_before_upscale=yes

[slot_2]
profile_name=2×补帧 + 2K｜极速
chain_1_min_resolution=1280x720
chain_1_max_resolution=1920x1080
chain_1_min_fps=0
chain_1_max_fps=0
chain_1_model_1_resize_height_before_upscale=720
chain_1_model_1_resize_factor_before_upscale=100
chain_1_model_1_name=2x_AnimeJaNai_HD_V3.1Sharp1_Performance_SPANF3_b5f48_unshuffle_fp16
chain_1_rife=yes
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
chain_1_rife_before_upscale=yes
chain_2_min_resolution=0x0
chain_2_max_resolution=1280x720
chain_2_min_fps=0
chain_2_max_fps=0
chain_2_model_1_resize_height_before_upscale=0
chain_2_model_1_resize_factor_before_upscale=100
chain_2_model_1_name=2x_AnimeJaNai_SD_V1beta34_Compact_1x3xHxW_dyn-HW_strong_fp16_op21_dynamo
chain_2_rife=yes
chain_2_rife_model=426
chain_2_rife_factor_numerator=2
chain_2_rife_factor_denominator=1
chain_2_rife_scene_detect_threshold=0.150
chain_2_rife_ensemble=no
chain_2_rife_before_upscale=yes
chain_3_min_resolution=1920x1080
chain_3_max_resolution=0x0
chain_3_min_fps=0
chain_3_max_fps=0
chain_3_rife=yes
chain_3_rife_model=426
chain_3_rife_factor_numerator=2
chain_3_rife_factor_denominator=1
chain_3_rife_scene_detect_threshold=0.150
chain_3_rife_ensemble=no
chain_3_rife_before_upscale=yes

[slot_3]
profile_name=新配置

[slot_4]
profile_name=新配置

[slot_5]
profile_name=新配置

[slot_6]
profile_name=新配置

[slot_7]
profile_name=新配置

[slot_8]
profile_name=新配置

[slot_9]
profile_name=新配置

