<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows7.0</TargetFramework>
		<RootNamespace>MpvNet.Windows</RootNamespace>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<PublishSingleFile>false</PublishSingleFile>
		<AssemblyName>mpv-AnimeFusion</AssemblyName>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon>mpv-icon.ico</ApplicationIcon>
		<FileVersion>1.3.0.0</FileVersion>
		<AssemblyVersion>1.3.0.0</AssemblyVersion>
		<InformationalVersion>1.3.0</InformationalVersion>
		<AnimeFusionRepositoryRoot>$([MSBuild]::GetDirectoryNameOfFileAbove('$(MSBuildThisFileDirectory)', 'release.json'))</AnimeFusionRepositoryRoot>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Misc\**" />
		<EmbeddedResource Remove="Misc\**" />
		<None Remove="Misc\**" />
		<Page Remove="Misc\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="mpv-icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MpvNet\MpvNet.csproj" />
		<ProjectReference Include="..\NGettext.Wpf\NGettext.Wpf.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Page Update="WPF\Views\AboutWindow.xaml">
			<Generator>MSBuild:Compile</Generator>
			<XamlRuntime>Wpf</XamlRuntime>
			<SubType>Designer</SubType>
		</Page>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BangumiNet.Api" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
	</ItemGroup>


  <Target Name="GeneratePortableAppHost" DependsOnTargets="_GetAppHostPaths">
    <CreateAppHost AppHostSourcePath="$(AppHostSourcePath)"
                   AppHostDestinationPath="$(PortableAppHostPath)"
                   AppBinaryName="app/$(AssemblyName).dll"
                   IntermediateAssembly="$(PortableAssembly)"
                   WindowsGraphicalUserInterface="true" />
  </Target>
</Project>
