<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0-windows</TargetFramework><Version>1.3.1</Version><AssemblyName>mpv-AnimeFusionUpdater</AssemblyName><Product>mpv-AnimeFusion</Product><Title>mpv-AnimeFusion Component Tool</Title><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><EnableDefaultCompileItems>false</EnableDefaultCompileItems><PublishSingleFile>false</PublishSingleFile><SelfContained>true</SelfContained><RuntimeIdentifier>win-x64</RuntimeIdentifier></PropertyGroup><ItemGroup><Compile Include="Updater.cs"/><PackageReference Include="System.Management" Version="10.0.0"/></ItemGroup></Project>
